global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
      monitor: 'mh9-starlite'
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']
  - job_name: 'machine'
    static_configs:
    - targets: ['172.17.0.1:9100']
